services:
  faucet:
    extends:
      file: docker-compose.yml
      service: faucet
    environment:
      SMF_BACKEND_NETWORK_DECIMALS: 12
      SMF_BACKEND_RPC_ENDPOINT: "wss://rpc.rococo.frequency.xyz/"

      SMF_BOT_MATRIX_SERVER: https://m.parity.io
      SMF_BOT_MATRIX_BOT_USER_ID: '@rococo-faucet-bot:matrix.org'
      SMF_BOT_DRIP_AMOUNT: 5000
      SMF_BOT_NETWORK_UNIT: XRQCY
